POST http://localhost:5000/api/articles HTTP/1.1
Content-Type: application/json

{
  "id": "anZ2uyw3nPHCqGoasIRkx",
  "title": "Борьба с прокрастинацией",
  "announce": [
    "Процессор заслуживает особого внимания.Он обязательно понравится геймерам со стажем.",
    "Освоить вёрстку несложно.Возьмите книгу новую книгу и закрепите все упражнения на практике.",
    "Рок - музыка всегда ассоциировалась с протестами.Так ли это на самом деле ?"
  ],
  "fullText": [
    "Этот смартфон — настоящая находка.Большой и яркий экран, мощнейший процессор — всё это в небольшом гаджете.",
    "Процессор заслуживает особого внимания.Он обязательно понравится геймерам со стажем.",
    "Достичь успеха помогут ежедневные повторения.",
    "Простые ежедневные упражнения помогут достичь успеха."
  ],
  "createdDate": "2019-11-18 21:21:15",
  "category": [
    "Программирование",
    "IT"
  ],
  "comments": [
    {
      "id": "W76KibmozY6Di_jBKgYES",
      "text": [
        "Давно не пользуюсь стационарными компьютерами. Ноутбуки победили.",
        "Плюсую, но слишком много буквы!"
      ]
    },
    {
      "id": "Er-PoJ9MmXWpmxw8wf17_",
      "text": [
        "Хочу такую же футболку :-)",
        "Это где ж такие красоты?",
        "Мне кажется или я уже читал это где-то?",
        "Планируете записать видосик на эту тему?"
      ]
    },
    {
      "id": "Jv0M_5gimowq3XJm8G5gc",
      "text": [
        "Мне не нравится ваш стиль. Ощущение, что вы меня поучаете."
      ]
    }
  ]
}
