--
-- PostgreSQL database dump
--

-- Dumped from database version 12.2
-- Dumped by pg_dump version 12.2

-- Started on 2020-08-29 17:52:34

-- ALTER DATABASE _DATABASE_NAME_ SET client_encoding = 'utf8'

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 202 (class 1259 OID 25685)
-- Name: articles; Type: TABLE; Schema: public; Owner: academy
--

CREATE TABLE public.articles (
    id integer NOT NULL,
    "authorId" bigint NOT NULL,
    title character varying(255) NOT NULL,
    img character varying(255),
    announce text,
    "fullText" text NOT NULL,
    "dateCreate" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.articles OWNER TO academy;

--
-- TOC entry 203 (class 1259 OID 25692)
-- Name: articles_category; Type: TABLE; Schema: public; Owner: academy
--

CREATE TABLE public.articles_category (
    id integer NOT NULL,
    "articleId" bigint NOT NULL,
    "categoryId" bigint NOT NULL
);


ALTER TABLE public.articles_category OWNER TO academy;

--
-- TOC entry 204 (class 1259 OID 25695)
-- Name: articles_category_id_seq; Type: SEQUENCE; Schema: public; Owner: academy
--

ALTER TABLE public.articles_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 25697)
-- Name: articles_id_seq; Type: SEQUENCE; Schema: public; Owner: academy
--

ALTER TABLE public.articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 206 (class 1259 OID 25699)
-- Name: categories; Type: TABLE; Schema: public; Owner: academy
--

CREATE TABLE public.categories (
    id integer NOT NULL,
    title character varying(100) NOT NULL
);


ALTER TABLE public.categories OWNER TO academy;

--
-- TOC entry 207 (class 1259 OID 25702)
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: academy
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 208 (class 1259 OID 25704)
-- Name: comments; Type: TABLE; Schema: public; Owner: academy
--

CREATE TABLE public.comments (
    id integer NOT NULL,
    "articleId" bigint NOT NULL,
    "authorId" bigint NOT NULL,
    text text NOT NULL,
    "dateCreate" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.comments OWNER TO academy;

--
-- TOC entry 209 (class 1259 OID 25711)
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: academy
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 25713)
-- Name: users; Type: TABLE; Schema: public; Owner: academy
--

CREATE TABLE public.users (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    surname character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    avatar character varying(255)
);


ALTER TABLE public.users OWNER TO academy;

--
-- TOC entry 211 (class 1259 OID 25719)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: academy
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2720 (class 2606 OID 25722)
-- Name: articles_category articles_category_pkey; Type: CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.articles_category
    ADD CONSTRAINT articles_category_pkey PRIMARY KEY (id);


--
-- TOC entry 2718 (class 2606 OID 25724)
-- Name: articles articles_pkey; Type: CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);


--
-- TOC entry 2722 (class 2606 OID 25726)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 2724 (class 2606 OID 25728)
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- TOC entry 2726 (class 2606 OID 25730)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 2716 (class 1259 OID 25731)
-- Name: article_title_index; Type: INDEX; Schema: public; Owner: academy
--

CREATE INDEX article_title_index ON public.articles USING btree (title);


--
-- TOC entry 2727 (class 2606 OID 25732)
-- Name: articles articles_author_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_author_id_fkey FOREIGN KEY ("authorId") REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 2728 (class 2606 OID 25737)
-- Name: articles_category articles_category_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.articles_category
    ADD CONSTRAINT articles_category_article_id_fkey FOREIGN KEY ("articleId") REFERENCES public.articles(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 2729 (class 2606 OID 25742)
-- Name: articles_category articles_category_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.articles_category
    ADD CONSTRAINT articles_category_category_id_fkey FOREIGN KEY ("categoryId") REFERENCES public.categories(id) NOT VALID;


--
-- TOC entry 2730 (class 2606 OID 25747)
-- Name: comments comments_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_article_id_fkey FOREIGN KEY ("articleId") REFERENCES public.articles(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 2731 (class 2606 OID 25752)
-- Name: comments comments_author_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_author_id_fkey FOREIGN KEY ("authorId") REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


-- Completed on 2020-08-29 17:52:35

--
-- PostgreSQL database dump complete
--

