--
-- PostgreSQL database dump
--

-- Dumped from database version 12.2
-- Dumped by pg_dump version 12.2

-- Started on 2020-07-28 12:25:49

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 202 (class 1259 OID 16705)
-- Name: articles; Type: TABLE; Schema: public; Owner: academy
--

CREATE TABLE public.articles (
    id integer NOT NULL,
    author_id bigint NOT NULL,
    title character varying(255) NOT NULL,
    img character varying(255),
    announce text,
    full_text text NOT NULL,
    date_create timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.articles OWNER TO academy;

--
-- TOC entry 203 (class 1259 OID 16712)
-- Name: articles_category; Type: TABLE; Schema: public; Owner: academy
--

CREATE TABLE public.articles_category (
    id integer NOT NULL,
    article_id bigint NOT NULL,
    category_id bigint NOT NULL
);


ALTER TABLE public.articles_category OWNER TO academy;

--
-- TOC entry 208 (class 1259 OID 16941)
-- Name: articles_category_id_seq; Type: SEQUENCE; Schema: public; Owner: academy
--

ALTER TABLE public.articles_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 16933)
-- Name: articles_id_seq; Type: SEQUENCE; Schema: public; Owner: academy
--

ALTER TABLE public.articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 204 (class 1259 OID 16715)
-- Name: categories; Type: TABLE; Schema: public; Owner: academy
--

CREATE TABLE public.categories (
    id integer NOT NULL,
    title character varying(100) NOT NULL
);


ALTER TABLE public.categories OWNER TO academy;

--
-- TOC entry 209 (class 1259 OID 16954)
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: academy
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 205 (class 1259 OID 16718)
-- Name: comments; Type: TABLE; Schema: public; Owner: academy
--

CREATE TABLE public.comments (
    id integer NOT NULL,
    article_id bigint NOT NULL,
    author_id bigint NOT NULL,
    text text NOT NULL,
    date_create timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.comments OWNER TO academy;

--
-- TOC entry 210 (class 1259 OID 16965)
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: academy
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 206 (class 1259 OID 16725)
-- Name: users; Type: TABLE; Schema: public; Owner: academy
--

CREATE TABLE public.users (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    surname character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    avatar character varying(255)
);


ALTER TABLE public.users OWNER TO academy;

--
-- TOC entry 211 (class 1259 OID 16986)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: academy
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2720 (class 2606 OID 16936)
-- Name: articles_category articles_category_pkey; Type: CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.articles_category
    ADD CONSTRAINT articles_category_pkey PRIMARY KEY (id);


--
-- TOC entry 2718 (class 2606 OID 16914)
-- Name: articles articles_pkey; Type: CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);


--
-- TOC entry 2722 (class 2606 OID 16944)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 2724 (class 2606 OID 16957)
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- TOC entry 2726 (class 2606 OID 16968)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 2716 (class 1259 OID 16754)
-- Name: article_title_index; Type: INDEX; Schema: public; Owner: academy
--

CREATE INDEX article_title_index ON public.articles USING btree (title);


--
-- TOC entry 2727 (class 2606 OID 16969)
-- Name: articles articles_author_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 2728 (class 2606 OID 16915)
-- Name: articles_category articles_category_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.articles_category
    ADD CONSTRAINT articles_category_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.articles(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 2729 (class 2606 OID 16945)
-- Name: articles_category articles_category_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.articles_category
    ADD CONSTRAINT articles_category_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id) NOT VALID;


--
-- TOC entry 2730 (class 2606 OID 16920)
-- Name: comments comments_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.articles(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 2731 (class 2606 OID 16974)
-- Name: comments comments_author_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: academy
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


-- Completed on 2020-07-28 12:25:50

--
-- PostgreSQL database dump complete
--

SELECT setval('public.articles_category_id_seq',1,true)
SELECT setval('public.articles_id_seq',1,true)
SELECT setval('public.categories_id_seq',1,true)
SELECT setval('public.comments_id_seq',1,true)
SELECT setval('public.users_id_seq',1,true)
